[package]
name = "ch08"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.12.1", features = ["v4"] }
tiny-keccak = { version= "2.0.2" , features = ["sha3"] }
hex = "0.4.3"
sha3 = "0.10.8"
tokio = { version = "1.43.0", features = ["time"] }
