[package]
name = "ch19"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
reqwest = { version = "0.12.9", features = ["blocking"] }
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread", "time"] }
